"""add phone num col

Revision ID: 3a7cf817a39c
Revises: 9248fdb6915b
Create Date: 2021-12-05 01:49:03.125696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a7cf817a39c'
down_revision = '9248fdb6915b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('phone_num', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'phone_num')
    # ### end Alembic commands ###
