"""remove phone col from posts

Revision ID: a2616da774fc
Revises: 3a7cf817a39c
Create Date: 2021-12-05 01:50:42.120322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2616da774fc'
down_revision = '3a7cf817a39c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'phone_num')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('phone_num', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
